#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_data_js.py
================
將 data/draw_results_verified.json 與 data/draw_results_1976_2002.json
打包成 data/data.js,以 window 全局變量方式注入,避免 fetch。

為什麼要這個檔案？
-----------------
* `fetch()` 在 `file://` 協議下會被瀏覽器 CORS 政策阻擋(ERR_FAILED)。
  使用者若直接雙擊 index.html 想離線查看,會看到「資料載入失敗」。
* 把 JSON 內容以 JS 變量形式內嵌,就能完全擺脫 fetch,適用於:
    - file:// 雙擊直接開啟
    - 任意 HTTP server (python -m http.server / nginx / InfinityFree ...)
    - 部署到任何純靜態主機

用法：
    python pipline/build_data_js.py                # 預設打包兩個 JSON
    python pipline/build_data_js.py --check        # 檢查 data.js 是否過期

輸出：
    data/data.js — 內容約為 3.8 MB,內含 window.DRAWS_DATA 與
    window.RECORDS_DATA 兩個全局變量。

更新流程：
    1) 跑 fetch_marksix_history.py / fetch_prizes.py 更新 JSON
    2) 跑本腳本重新生成 data.js
    3) 重新整理瀏覽器即可
"""

import argparse
import gzip
import json
import os
import sys
import time
from pathlib import Path

# ---------------------------------------------------------------------------
# 路徑
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
DATA_DIR = PROJECT_ROOT / 'data'
DRAWS_JSON = DATA_DIR / 'draw_results_verified.json'
RECORDS_JSON = DATA_DIR / 'draw_results_1976_2002.json'
OUTPUT_JS = DATA_DIR / 'data.js'

JS_HEADER = """/* ============================================================
 * 香港六合彩資訊網站 — 內嵌資料集 (auto-generated by build_data_js.py)
 * 請勿手動編輯;若要更新,請修改對應的 JSON 後重新執行構建腳本。
 * 用途:避免 file:// 協議下 fetch 被 CORS 阻擋,雙擊 index.html 即可瀏覽。
 * ============================================================ */
window.DRAWS_DATA = {DRAWS_JSON};
window.RECORDS_DATA = {RECORDS_JSON};
"""


def load_json(path: Path) -> dict:
    if not path.exists():
        sys.exit(f'❌ 找不到 {path}')
    with path.open('r', encoding='utf-8') as f:
        return json.load(f)


def write_data_js(draws: dict, records: dict) -> None:
    # 緊湊 JSON (separators=(',', ':')) 可比預設縮排省 30-40% 體積
    draws_str = json.dumps(draws, ensure_ascii=False, separators=(',', ':'))
    records_str = json.dumps(records, ensure_ascii=False, separators=(',', ':'))

    content = JS_HEADER.format(DRAWS_JSON=draws_str, RECORDS_JSON=records_str)

    OUTPUT_JS.write_text(content, encoding='utf-8')

    raw_size = OUTPUT_JS.stat().st_size
    gz_size = len(gzip.compress(content.encode('utf-8')))
    print(f'  ✓ 寫入 {OUTPUT_JS.relative_to(PROJECT_ROOT)}')
    print(f'    原始大小: {raw_size / 1024 / 1024:.2f} MB ({raw_size:,} bytes)')
    print(f'    gzip 估算: {gz_size / 1024:.1f} KB (HTTP 傳輸實際大小)')


def check_freshness() -> None:
    """檢查 data.js 是否比 JSON 新;若否則提示重新生成。"""
    if not OUTPUT_JS.exists():
        sys.exit(f'❌ {OUTPUT_JS} 不存在,請先執行 `python {SCRIPT_DIR.name}/build_data_js.py`')
    js_mtime = OUTPUT_JS.stat().st_mtime
    stale = []
    for p in (DRAWS_JSON, RECORDS_JSON):
        if not p.exists():
            continue
        if p.stat().st_mtime > js_mtime:
            stale.append(p.name)
    if stale:
        print(f'⚠️  以下 JSON 比 data.js 新,請重新生成: {", ".join(stale)}')
        sys.exit(1)
    print(f'✓ data.js 已是最新')


def main() -> None:
    parser = argparse.ArgumentParser(description='打包 JSON → data.js')
    parser.add_argument('--check', action='store_true', help='僅檢查 data.js 是否過期')
    args = parser.parse_args()

    if args.check:
        check_freshness()
        return

    print('📦 打包內嵌資料集...')
    draws = load_json(DRAWS_JSON)
    records = load_json(RECORDS_JSON)
    print(f'  · draws:    {len(draws.get("draws", []))} 期')
    print(f'  · records:  {len(records.get("records", []))} 期')

    t0 = time.time()
    write_data_js(draws, records)
    print(f'⏱️  完成,用時 {time.time() - t0:.1f}s')


if __name__ == '__main__':
    main()
